// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rendering_job.proto

#include "rendering_job.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace agent {
namespace package {
namespace renderer {
PROTOBUF_CONSTEXPR project_files::project_files(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.relative_path_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.download_url_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct project_filesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR project_filesDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~project_filesDefaultTypeInternal() {}
  union {
    project_files _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 project_filesDefaultTypeInternal _project_files_default_instance_;
PROTOBUF_CONSTEXPR render_project::render_project(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.files_)*/{}
  , /*decltype(_impl_.project_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.blender_version_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.blend_file_)*/nullptr
  , /*decltype(_impl_.begin_frame_)*/0u
  , /*decltype(_impl_.end_frame_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct render_projectDefaultTypeInternal {
  PROTOBUF_CONSTEXPR render_projectDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~render_projectDefaultTypeInternal() {}
  union {
    render_project _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 render_projectDefaultTypeInternal _render_project_default_instance_;
PROTOBUF_CONSTEXPR rendering_job::rendering_job(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.job_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.project_)*/nullptr
  , /*decltype(_impl_.frame_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct rendering_jobDefaultTypeInternal {
  PROTOBUF_CONSTEXPR rendering_jobDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~rendering_jobDefaultTypeInternal() {}
  union {
    rendering_job _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 rendering_jobDefaultTypeInternal _rendering_job_default_instance_;
}  // namespace renderer
}  // namespace package
}  // namespace agent
static ::_pb::Metadata file_level_metadata_rendering_5fjob_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_rendering_5fjob_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_rendering_5fjob_2eproto = nullptr;

const uint32_t TableStruct_rendering_5fjob_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::agent::package::renderer::project_files, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::agent::package::renderer::project_files, _impl_.relative_path_),
  PROTOBUF_FIELD_OFFSET(::agent::package::renderer::project_files, _impl_.download_url_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::agent::package::renderer::render_project, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::agent::package::renderer::render_project, _impl_.project_id_),
  PROTOBUF_FIELD_OFFSET(::agent::package::renderer::render_project, _impl_.begin_frame_),
  PROTOBUF_FIELD_OFFSET(::agent::package::renderer::render_project, _impl_.end_frame_),
  PROTOBUF_FIELD_OFFSET(::agent::package::renderer::render_project, _impl_.files_),
  PROTOBUF_FIELD_OFFSET(::agent::package::renderer::render_project, _impl_.blend_file_),
  PROTOBUF_FIELD_OFFSET(::agent::package::renderer::render_project, _impl_.blender_version_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::agent::package::renderer::rendering_job, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::agent::package::renderer::rendering_job, _impl_.job_id_),
  PROTOBUF_FIELD_OFFSET(::agent::package::renderer::rendering_job, _impl_.frame_),
  PROTOBUF_FIELD_OFFSET(::agent::package::renderer::rendering_job, _impl_.project_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::agent::package::renderer::project_files)},
  { 8, -1, -1, sizeof(::agent::package::renderer::render_project)},
  { 20, -1, -1, sizeof(::agent::package::renderer::rendering_job)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::agent::package::renderer::_project_files_default_instance_._instance,
  &::agent::package::renderer::_render_project_default_instance_._instance,
  &::agent::package::renderer::_rendering_job_default_instance_._instance,
};

const char descriptor_table_protodef_rendering_5fjob_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023rendering_job.proto\022\026agent.package.ren"
  "derer\"<\n\rproject_files\022\025\n\rrelative_path\030"
  "\001 \001(\t\022\024\n\014download_url\030\002 \001(\t\"\326\001\n\016render_p"
  "roject\022\022\n\nproject_id\030\001 \001(\t\022\023\n\013begin_fram"
  "e\030\002 \001(\r\022\021\n\tend_frame\030\003 \001(\r\0224\n\005files\030\004 \003("
  "\0132%.agent.package.renderer.project_files"
  "\0229\n\nblend_file\030\005 \001(\0132%.agent.package.ren"
  "derer.project_files\022\027\n\017blender_version\030\006"
  " \001(\t\"g\n\rrendering_job\022\016\n\006job_id\030\001 \001(\t\022\r\n"
  "\005frame\030\002 \001(\r\0227\n\007project\030\003 \001(\0132&.agent.pa"
  "ckage.renderer.render_projectb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_rendering_5fjob_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_rendering_5fjob_2eproto = {
    false, false, 437, descriptor_table_protodef_rendering_5fjob_2eproto,
    "rendering_job.proto",
    &descriptor_table_rendering_5fjob_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_rendering_5fjob_2eproto::offsets,
    file_level_metadata_rendering_5fjob_2eproto, file_level_enum_descriptors_rendering_5fjob_2eproto,
    file_level_service_descriptors_rendering_5fjob_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_rendering_5fjob_2eproto_getter() {
  return &descriptor_table_rendering_5fjob_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_rendering_5fjob_2eproto(&descriptor_table_rendering_5fjob_2eproto);
namespace agent {
namespace package {
namespace renderer {

// ===================================================================

class project_files::_Internal {
 public:
};

project_files::project_files(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:agent.package.renderer.project_files)
}
project_files::project_files(const project_files& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  project_files* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.relative_path_){}
    , decltype(_impl_.download_url_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.relative_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.relative_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_relative_path().empty()) {
    _this->_impl_.relative_path_.Set(from._internal_relative_path(), 
      _this->GetArenaForAllocation());
  }
  _impl_.download_url_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.download_url_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_download_url().empty()) {
    _this->_impl_.download_url_.Set(from._internal_download_url(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:agent.package.renderer.project_files)
}

inline void project_files::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.relative_path_){}
    , decltype(_impl_.download_url_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.relative_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.relative_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.download_url_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.download_url_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

project_files::~project_files() {
  // @@protoc_insertion_point(destructor:agent.package.renderer.project_files)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void project_files::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.relative_path_.Destroy();
  _impl_.download_url_.Destroy();
}

void project_files::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void project_files::Clear() {
// @@protoc_insertion_point(message_clear_start:agent.package.renderer.project_files)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.relative_path_.ClearToEmpty();
  _impl_.download_url_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* project_files::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string relative_path = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_relative_path();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "agent.package.renderer.project_files.relative_path"));
        } else
          goto handle_unusual;
        continue;
      // string download_url = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_download_url();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "agent.package.renderer.project_files.download_url"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* project_files::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:agent.package.renderer.project_files)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string relative_path = 1;
  if (!this->_internal_relative_path().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_relative_path().data(), static_cast<int>(this->_internal_relative_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "agent.package.renderer.project_files.relative_path");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_relative_path(), target);
  }

  // string download_url = 2;
  if (!this->_internal_download_url().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_download_url().data(), static_cast<int>(this->_internal_download_url().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "agent.package.renderer.project_files.download_url");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_download_url(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:agent.package.renderer.project_files)
  return target;
}

size_t project_files::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:agent.package.renderer.project_files)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string relative_path = 1;
  if (!this->_internal_relative_path().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_relative_path());
  }

  // string download_url = 2;
  if (!this->_internal_download_url().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_download_url());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData project_files::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    project_files::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*project_files::GetClassData() const { return &_class_data_; }


void project_files::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<project_files*>(&to_msg);
  auto& from = static_cast<const project_files&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:agent.package.renderer.project_files)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_relative_path().empty()) {
    _this->_internal_set_relative_path(from._internal_relative_path());
  }
  if (!from._internal_download_url().empty()) {
    _this->_internal_set_download_url(from._internal_download_url());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void project_files::CopyFrom(const project_files& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:agent.package.renderer.project_files)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool project_files::IsInitialized() const {
  return true;
}

void project_files::InternalSwap(project_files* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.relative_path_, lhs_arena,
      &other->_impl_.relative_path_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.download_url_, lhs_arena,
      &other->_impl_.download_url_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata project_files::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_rendering_5fjob_2eproto_getter, &descriptor_table_rendering_5fjob_2eproto_once,
      file_level_metadata_rendering_5fjob_2eproto[0]);
}

// ===================================================================

class render_project::_Internal {
 public:
  static const ::agent::package::renderer::project_files& blend_file(const render_project* msg);
};

const ::agent::package::renderer::project_files&
render_project::_Internal::blend_file(const render_project* msg) {
  return *msg->_impl_.blend_file_;
}
render_project::render_project(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:agent.package.renderer.render_project)
}
render_project::render_project(const render_project& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  render_project* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.files_){from._impl_.files_}
    , decltype(_impl_.project_id_){}
    , decltype(_impl_.blender_version_){}
    , decltype(_impl_.blend_file_){nullptr}
    , decltype(_impl_.begin_frame_){}
    , decltype(_impl_.end_frame_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.project_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.project_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_project_id().empty()) {
    _this->_impl_.project_id_.Set(from._internal_project_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.blender_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.blender_version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_blender_version().empty()) {
    _this->_impl_.blender_version_.Set(from._internal_blender_version(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_blend_file()) {
    _this->_impl_.blend_file_ = new ::agent::package::renderer::project_files(*from._impl_.blend_file_);
  }
  ::memcpy(&_impl_.begin_frame_, &from._impl_.begin_frame_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.end_frame_) -
    reinterpret_cast<char*>(&_impl_.begin_frame_)) + sizeof(_impl_.end_frame_));
  // @@protoc_insertion_point(copy_constructor:agent.package.renderer.render_project)
}

inline void render_project::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.files_){arena}
    , decltype(_impl_.project_id_){}
    , decltype(_impl_.blender_version_){}
    , decltype(_impl_.blend_file_){nullptr}
    , decltype(_impl_.begin_frame_){0u}
    , decltype(_impl_.end_frame_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.project_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.project_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.blender_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.blender_version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

render_project::~render_project() {
  // @@protoc_insertion_point(destructor:agent.package.renderer.render_project)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void render_project::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.files_.~RepeatedPtrField();
  _impl_.project_id_.Destroy();
  _impl_.blender_version_.Destroy();
  if (this != internal_default_instance()) delete _impl_.blend_file_;
}

void render_project::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void render_project::Clear() {
// @@protoc_insertion_point(message_clear_start:agent.package.renderer.render_project)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.files_.Clear();
  _impl_.project_id_.ClearToEmpty();
  _impl_.blender_version_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.blend_file_ != nullptr) {
    delete _impl_.blend_file_;
  }
  _impl_.blend_file_ = nullptr;
  ::memset(&_impl_.begin_frame_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.end_frame_) -
      reinterpret_cast<char*>(&_impl_.begin_frame_)) + sizeof(_impl_.end_frame_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* render_project::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string project_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_project_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "agent.package.renderer.render_project.project_id"));
        } else
          goto handle_unusual;
        continue;
      // uint32 begin_frame = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.begin_frame_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 end_frame = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.end_frame_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .agent.package.renderer.project_files files = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_files(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      // .agent.package.renderer.project_files blend_file = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_blend_file(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string blender_version = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_blender_version();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "agent.package.renderer.render_project.blender_version"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* render_project::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:agent.package.renderer.render_project)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string project_id = 1;
  if (!this->_internal_project_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_project_id().data(), static_cast<int>(this->_internal_project_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "agent.package.renderer.render_project.project_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_project_id(), target);
  }

  // uint32 begin_frame = 2;
  if (this->_internal_begin_frame() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_begin_frame(), target);
  }

  // uint32 end_frame = 3;
  if (this->_internal_end_frame() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_end_frame(), target);
  }

  // repeated .agent.package.renderer.project_files files = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_files_size()); i < n; i++) {
    const auto& repfield = this->_internal_files(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  // .agent.package.renderer.project_files blend_file = 5;
  if (this->_internal_has_blend_file()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::blend_file(this),
        _Internal::blend_file(this).GetCachedSize(), target, stream);
  }

  // string blender_version = 6;
  if (!this->_internal_blender_version().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_blender_version().data(), static_cast<int>(this->_internal_blender_version().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "agent.package.renderer.render_project.blender_version");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_blender_version(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:agent.package.renderer.render_project)
  return target;
}

size_t render_project::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:agent.package.renderer.render_project)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .agent.package.renderer.project_files files = 4;
  total_size += 1UL * this->_internal_files_size();
  for (const auto& msg : this->_impl_.files_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string project_id = 1;
  if (!this->_internal_project_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_project_id());
  }

  // string blender_version = 6;
  if (!this->_internal_blender_version().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_blender_version());
  }

  // .agent.package.renderer.project_files blend_file = 5;
  if (this->_internal_has_blend_file()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.blend_file_);
  }

  // uint32 begin_frame = 2;
  if (this->_internal_begin_frame() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_begin_frame());
  }

  // uint32 end_frame = 3;
  if (this->_internal_end_frame() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_end_frame());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData render_project::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    render_project::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*render_project::GetClassData() const { return &_class_data_; }


void render_project::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<render_project*>(&to_msg);
  auto& from = static_cast<const render_project&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:agent.package.renderer.render_project)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.files_.MergeFrom(from._impl_.files_);
  if (!from._internal_project_id().empty()) {
    _this->_internal_set_project_id(from._internal_project_id());
  }
  if (!from._internal_blender_version().empty()) {
    _this->_internal_set_blender_version(from._internal_blender_version());
  }
  if (from._internal_has_blend_file()) {
    _this->_internal_mutable_blend_file()->::agent::package::renderer::project_files::MergeFrom(
        from._internal_blend_file());
  }
  if (from._internal_begin_frame() != 0) {
    _this->_internal_set_begin_frame(from._internal_begin_frame());
  }
  if (from._internal_end_frame() != 0) {
    _this->_internal_set_end_frame(from._internal_end_frame());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void render_project::CopyFrom(const render_project& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:agent.package.renderer.render_project)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool render_project::IsInitialized() const {
  return true;
}

void render_project::InternalSwap(render_project* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.files_.InternalSwap(&other->_impl_.files_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.project_id_, lhs_arena,
      &other->_impl_.project_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.blender_version_, lhs_arena,
      &other->_impl_.blender_version_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(render_project, _impl_.end_frame_)
      + sizeof(render_project::_impl_.end_frame_)
      - PROTOBUF_FIELD_OFFSET(render_project, _impl_.blend_file_)>(
          reinterpret_cast<char*>(&_impl_.blend_file_),
          reinterpret_cast<char*>(&other->_impl_.blend_file_));
}

::PROTOBUF_NAMESPACE_ID::Metadata render_project::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_rendering_5fjob_2eproto_getter, &descriptor_table_rendering_5fjob_2eproto_once,
      file_level_metadata_rendering_5fjob_2eproto[1]);
}

// ===================================================================

class rendering_job::_Internal {
 public:
  static const ::agent::package::renderer::render_project& project(const rendering_job* msg);
};

const ::agent::package::renderer::render_project&
rendering_job::_Internal::project(const rendering_job* msg) {
  return *msg->_impl_.project_;
}
rendering_job::rendering_job(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:agent.package.renderer.rendering_job)
}
rendering_job::rendering_job(const rendering_job& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  rendering_job* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.job_id_){}
    , decltype(_impl_.project_){nullptr}
    , decltype(_impl_.frame_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.job_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.job_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_job_id().empty()) {
    _this->_impl_.job_id_.Set(from._internal_job_id(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_project()) {
    _this->_impl_.project_ = new ::agent::package::renderer::render_project(*from._impl_.project_);
  }
  _this->_impl_.frame_ = from._impl_.frame_;
  // @@protoc_insertion_point(copy_constructor:agent.package.renderer.rendering_job)
}

inline void rendering_job::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.job_id_){}
    , decltype(_impl_.project_){nullptr}
    , decltype(_impl_.frame_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.job_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.job_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

rendering_job::~rendering_job() {
  // @@protoc_insertion_point(destructor:agent.package.renderer.rendering_job)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void rendering_job::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.job_id_.Destroy();
  if (this != internal_default_instance()) delete _impl_.project_;
}

void rendering_job::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void rendering_job::Clear() {
// @@protoc_insertion_point(message_clear_start:agent.package.renderer.rendering_job)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.job_id_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.project_ != nullptr) {
    delete _impl_.project_;
  }
  _impl_.project_ = nullptr;
  _impl_.frame_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* rendering_job::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string job_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_job_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "agent.package.renderer.rendering_job.job_id"));
        } else
          goto handle_unusual;
        continue;
      // uint32 frame = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.frame_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .agent.package.renderer.render_project project = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_project(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* rendering_job::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:agent.package.renderer.rendering_job)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string job_id = 1;
  if (!this->_internal_job_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_job_id().data(), static_cast<int>(this->_internal_job_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "agent.package.renderer.rendering_job.job_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_job_id(), target);
  }

  // uint32 frame = 2;
  if (this->_internal_frame() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_frame(), target);
  }

  // .agent.package.renderer.render_project project = 3;
  if (this->_internal_has_project()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::project(this),
        _Internal::project(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:agent.package.renderer.rendering_job)
  return target;
}

size_t rendering_job::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:agent.package.renderer.rendering_job)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string job_id = 1;
  if (!this->_internal_job_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_job_id());
  }

  // .agent.package.renderer.render_project project = 3;
  if (this->_internal_has_project()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.project_);
  }

  // uint32 frame = 2;
  if (this->_internal_frame() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_frame());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData rendering_job::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    rendering_job::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*rendering_job::GetClassData() const { return &_class_data_; }


void rendering_job::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<rendering_job*>(&to_msg);
  auto& from = static_cast<const rendering_job&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:agent.package.renderer.rendering_job)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_job_id().empty()) {
    _this->_internal_set_job_id(from._internal_job_id());
  }
  if (from._internal_has_project()) {
    _this->_internal_mutable_project()->::agent::package::renderer::render_project::MergeFrom(
        from._internal_project());
  }
  if (from._internal_frame() != 0) {
    _this->_internal_set_frame(from._internal_frame());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void rendering_job::CopyFrom(const rendering_job& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:agent.package.renderer.rendering_job)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool rendering_job::IsInitialized() const {
  return true;
}

void rendering_job::InternalSwap(rendering_job* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.job_id_, lhs_arena,
      &other->_impl_.job_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(rendering_job, _impl_.frame_)
      + sizeof(rendering_job::_impl_.frame_)
      - PROTOBUF_FIELD_OFFSET(rendering_job, _impl_.project_)>(
          reinterpret_cast<char*>(&_impl_.project_),
          reinterpret_cast<char*>(&other->_impl_.project_));
}

::PROTOBUF_NAMESPACE_ID::Metadata rendering_job::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_rendering_5fjob_2eproto_getter, &descriptor_table_rendering_5fjob_2eproto_once,
      file_level_metadata_rendering_5fjob_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace renderer
}  // namespace package
}  // namespace agent
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::agent::package::renderer::project_files*
Arena::CreateMaybeMessage< ::agent::package::renderer::project_files >(Arena* arena) {
  return Arena::CreateMessageInternal< ::agent::package::renderer::project_files >(arena);
}
template<> PROTOBUF_NOINLINE ::agent::package::renderer::render_project*
Arena::CreateMaybeMessage< ::agent::package::renderer::render_project >(Arena* arena) {
  return Arena::CreateMessageInternal< ::agent::package::renderer::render_project >(arena);
}
template<> PROTOBUF_NOINLINE ::agent::package::renderer::rendering_job*
Arena::CreateMaybeMessage< ::agent::package::renderer::rendering_job >(Arena* arena) {
  return Arena::CreateMessageInternal< ::agent::package::renderer::rendering_job >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
